name: mobile_app_frontend
description: Audiolibra mobile application for audiobook browsing, purchasing, library, and playback.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  audioplayers: ^6.5.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/moby_dick_cover.jpg
